dataset:
  seq_len: 1024
  feature_size: 24
  label_dim: 30
  batch_size: 32
  split_size: 0.8
  max_iteration: 1000
  save_iteration: 100
  lr: 0.001

model:
  inception_filter: 64
  fcn_filter: 64
  dropout: 0.2
  depth: 6
  fcn_layers: 4
  kernels: [10,20,40]
  use_residual: True
  use_bottleneck: True
  use_embedding: False

csv_fields:
 - train_data
 - aug_data
 - test_data
 - epoch
 - accuracy


