dataset:
  seq_len: 1024
  feature_size: 24
  label_dim: 30
  batch_size: 32
  split_size: 0.8
  label_type: 'task'
  max_iteration: 1000
  save_iteration: 100
  lr: 0.001

model:
  filter_size: 32
  dropout: 0.1
  depth: 6
  kernels: [10,20,40]
  use_residual: True
  use_bottleneck: True
  use_attn: False


